### ISSUE TITLE
More example in plain Javascript

### ISSUE THREAD

**Issue by siriokun** [wayscript/wayscript-js-legacy#1]

**Comment by jeffbuswell** [comment]
@siriokun Will do! 👍

**Comment by jeffbuswell** [comment]
@siriokun I added an example app here: [wayscript/js-to-gmail-example](https://github.com/wayscript/js-to-gmail-example)

Essentially, using the wayscript-js library with plain JavaScript will look something like this:

1) Include the library in your project: 

    ```html
    <script src="https://cdn.wayscript.com/static/js/api/wayscript.0.0.7.js"></script>
    ```

2) Run a WayScript program from your JS code:

    ```javascript
    const prog_id = 0;
    const secret_key = '';

    wayscript.apiKey = secret_key;

    wayscript.runProgram( prog_id, values )
      .onSuccess( function ( responseText ) {
        console.log( responseText );
      } ).onError( function ( responseText ) {
      console.log( responseText );
    } );
    ```

**Comment by jeffbuswell** [comment]
@siriokun, I'm going to go ahead and close this issue. Please reach out if you need anything else!
